.PHONY: check all fetch-markets fetch-investing fetch-crypto fetch-dev bronze crisis diagrams \
        tables appendix figures h3-extra

# The graph separates network fetches from local rebuilds. Anything that talks
# to an external service (Binance, Yahoo, FRED, World Bank) is a manual target:
# it never runs as a side effect of a local build. Everything derivable from
# files already on disk (including the committed manual raw inputs under
# data/raw/) is wired into the dependency graph and rebuilds only when its
# inputs change.

# ---- Bronze ----
# Yahoo/FRED market data is a network fetch: `make fetch-markets`.
# Investing.com series are parsed locally from committed CSVs: `make fetch-investing`.
# Binance 1-minute crypto data is a network fetch: `make fetch-crypto`.
BRONZE_INV := data/parquet/investing_manual.parquet
BRONZE_EQ  := data/parquet/equity.parquet
BRONZE_FX  := data/parquet/fx.parquet

$(BRONZE_INV): scripts/fetch_investing.py src/fetchers/investing_csv_parser.py \
               $(wildcard data/raw/investing_csvs/*_equity.csv) \
               $(wildcard data/raw/investing_csvs/*_fx.csv)
	uv run python scripts/fetch_investing.py

fetch-markets:
	uv run python scripts/fetch_markets.py

fetch-investing: $(BRONZE_INV)

fetch-crypto:
	uv run python scripts/fetch_crypto.py

bronze: fetch-investing fetch-markets fetch-crypto

# ---- Silver ----
# clean_crypto fails loudly if the monthly bronze files are absent; run
# `make fetch-crypto` first on a fresh clone.
SILVER := data/parquet/clean
EQ     := $(SILVER)/equity.parquet
FX     := $(SILVER)/fx.parquet
BTC    := $(SILVER)/btc_1min.parquet
ETH    := $(SILVER)/eth_1min.parquet

clean: $(EQ) $(FX) $(BTC) $(ETH)

$(EQ) $(FX) &: src/clean/clean_markets.py src/quality/schemas.py config/countries.yaml \
               $(BRONZE_INV) $(BRONZE_EQ) $(BRONZE_FX)
	uv run python -m src.clean.clean_markets

$(BTC): src/clean/clean_crypto.py src/quality/schemas.py \
        $(wildcard data/parquet/crypto/btcusdt/*.parquet)
	uv run python -m src.clean.clean_crypto --asset btc

$(ETH): src/clean/clean_crypto.py src/quality/schemas.py \
        $(wildcard data/parquet/crypto/ethusdt/*.parquet)
	uv run python -m src.clean.clean_crypto --asset eth

# ---- ERR reference table ----
# config/err_float.csv is generated by build_err_table.py from countries.yaml,
# not hand-edited. Curation lives in the script; adding a country to
# countries.yaml gives it a -1 sentinel until it is curated, and the panel
# build then fails loudly naming the country instead of producing a silent
# NaN merge downstream.
ERR_CSV := config/err_float.csv

$(ERR_CSV): scripts/build_err_table.py config/countries.yaml
	uv run python scripts/build_err_table.py

# ---- KAOPEN ----
# Local parse of the committed Chinn-Ito workbook.
KAOPEN := data/parquet/kaopen.parquet

$(KAOPEN): scripts/fetch_kaopen.py data/raw/kaopen_2023.xls config/ingestion_settings.yaml
	uv run python scripts/fetch_kaopen.py

# ---- Gold ----
GOLD       := data/parquet/gold
BTC_RV     := $(GOLD)/btc_rv_daily.parquet
ETH_RV     := $(GOLD)/eth_rv_daily.parquet
PANEL      := $(GOLD)/panel.parquet

features: $(BTC_RV) $(ETH_RV) $(PANEL)

$(BTC_RV): src/features/realized_vol.py src/quality/schemas.py $(BTC)
	uv run python -m src.features.realized_vol --asset btc

$(ETH_RV): src/features/realized_vol.py src/quality/schemas.py $(ETH)
	uv run python -m src.features.realized_vol --asset eth

$(PANEL): src/features/build_panel.py src/features/returns.py src/quality/schemas.py \
          $(EQ) $(FX) $(BTC_RV) $(ETH_RV) \
          data/parquet/controls.parquet $(KAOPEN) \
          config/countries.yaml $(ERR_CSV)
	uv run python -m src.features.build_panel

# ---- Sample: frozen, configuration-based, data-quality-only inclusion ----
# The audit engine measures coverage and staleness per country and channel and
# applies the frozen rule in config/sample_rule.yaml. Editing the thresholds
# re-derives membership, which binds the Step 2 regressions (panel_prep sets
# the spillover share to NaN for channels that did not qualify). Local.
SAMPLE := $(GOLD)/sample_membership.parquet

sample: $(SAMPLE)
$(SAMPLE): src/sample/audit.py src/sample/rule.py src/sample/report.py \
           src/sample/build.py config/sample_rule.yaml $(EQ) $(FX)
	uv run python -m src.sample.build

# Crisis flag (hyperinflation or devaluation country-years; kept and flagged,
# used in leave-out robustness). Network fetch of World Bank CPI, kept manual
# like the other external fetches.
crisis: $(GOLD)/crisis_flags.parquet
$(GOLD)/crisis_flags.parquet: src/sample/crisis.py config/sample_rule.yaml $(SAMPLE) $(FX)
	uv run python -m src.sample.crisis

# ---- Quality ----
check:
	uv run pytest tests/

# ---- Spillovers (Step 1) ----
SPILL := $(GOLD)/spillovers.parquet

spillovers: $(SPILL)
$(SPILL): src/spillovers/rolling_dy.py src/spillovers/build_spillovers.py \
          src/quality/schemas.py $(PANEL)
	uv run python -m src.spillovers.build_spillovers

# ---- Step 2: core panel (H2 and H3) ----
DEV        := data/parquet/country_dev.parquet
STEP2      := $(GOLD)/step2_analysis.parquet
STEP2_COEF := $(GOLD)/step2_panel_coefs.parquet

fetch-dev:
	uv run python scripts/fetch_worldbank_dev.py

$(STEP2): src/models/panel_prep.py src/quality/schemas.py $(SPILL) $(PANEL) $(DEV) $(SAMPLE)
	uv run python -m src.models.panel_prep

panel: $(STEP2_COEF)
$(STEP2_COEF): src/models/panel_regression.py $(STEP2)
	uv run python -m src.models.panel_regression

# ---- Step 2 robustness (winsorized log-odds outcome and 60-day window) ----
SPILL60 := $(GOLD)/spillovers_w60.parquet
ROBUST  := $(GOLD)/step2_robustness_coefs.parquet

$(SPILL60): src/spillovers/rolling_dy.py src/spillovers/build_spillovers.py $(PANEL)
	uv run python -m src.spillovers.build_spillovers --window 60

robustness: $(ROBUST)
$(ROBUST): src/models/robustness.py src/models/panel_prep.py src/models/panel_regression.py \
           $(SPILL) $(SPILL60) $(DEV) $(PANEL)
	uv run python -m src.models.robustness

# ---- Step 2 decomposition (share vs level and trivariate dollar system) ----
COMPONENTS := $(GOLD)/spillover_components.parquet
TRIVAR     := $(GOLD)/spillover_3var.parquet

$(COMPONENTS): src/spillovers/rolling_dy.py src/spillovers/build_decomposition.py $(PANEL)
	uv run python -m src.spillovers.build_decomposition --part components

$(TRIVAR): src/spillovers/rolling_dy.py src/spillovers/build_decomposition.py $(PANEL)
	uv run python -m src.spillovers.build_decomposition --part 3var

DECOMP := $(GOLD)/decomp_coefs.parquet

decomposition: $(DECOMP)
$(DECOMP): src/models/decomposition.py src/models/panel_regression.py src/models/robustness.py \
           $(STEP2) $(COMPONENTS) $(TRIVAR)
	uv run python -m src.models.decomposition

# ---- VAR-stability (spectral-radius) diagnostics ----
# Re-estimates each rolling window's VAR to record its companion spectral
# radius, then re-runs H1/H2/H3 excluding windows with a radius of one or
# more, next to an in-run unfiltered baseline. Additive: it never rebuilds the
# frozen headline outputs. See notebooks/09_spectral_radius_robustness.ipynb.
STABILITY    := $(GOLD)/spillovers_stability.parquet
STABILITYCMP := $(GOLD)/stability_comparison.parquet

stability: $(STABILITY)
$(STABILITY): src/spillovers/rolling_dy.py src/spillovers/build_stability.py \
              src/quality/schemas.py $(SPILL) $(PANEL)
	uv run python -m src.spillovers.build_stability

stability-coefs: $(STABILITYCMP)
$(STABILITYCMP): src/models/robustness_stability.py src/models/decomposition.py \
              src/models/panel_regression.py $(STABILITY) $(STEP2) $(COMPONENTS) $(TRIVAR)
	uv run python -m src.models.robustness_stability --thresholds 1.0,0.99

# ---- Step 2 leave-outs (crisis-country drop, Ethereum transmitter, trivariate) ----
SPILL_ETH := $(GOLD)/spillovers_eth.parquet
LEAVEOUT  := $(GOLD)/step2_leaveout_coefs.parquet

$(SPILL_ETH): src/spillovers/rolling_dy.py src/spillovers/build_spillovers.py $(PANEL)
	uv run python -m src.spillovers.build_spillovers --crypto eth_rv

leaveouts: $(LEAVEOUT)
$(LEAVEOUT): src/models/robustness_leaveouts.py src/models/panel_prep.py \
           src/models/panel_regression.py src/models/robustness.py \
           $(STEP2) $(SPILL_ETH) $(TRIVAR) $(GOLD)/crisis_flags.parquet
	uv run python -m src.models.robustness_leaveouts

# ---- Step 2 horse races (global-risk and development confounds) ----
HORSERACE    := $(GOLD)/horse_race_coefs.parquet
DEVHORSERACE := $(GOLD)/dev_horse_race_coefs.parquet

horse-race: $(HORSERACE)
$(HORSERACE) $(DEVHORSERACE): scripts/horse_race_global_risk.py \
           src/models/panel_regression.py src/models/robustness.py $(STEP2)
	uv run python scripts/horse_race_global_risk.py

# ---- Extended H3 diagnostics (two-way FE rung and equity placebo) ----
h3-extra:
	uv run python scripts/h3_regime_direct.py

# ---- Generated tables, appendices, and figures ----
# All built from the gold outputs and config; nothing is hand-transcribed.
# These write into a local thesis/ folder that stays out of version control.
tables:
	uv run python scripts/make_tables.py

appendix:
	uv run python scripts/make_appendix_a.py
	uv run python scripts/make_appendix_b.py
	uv run python scripts/make_appendix_d.py

figures:
	uv run python scripts/make_figures.py
	uv run python scripts/make_fig_3_2.py
	uv run python scripts/make_fig_4_twostep.py

# ---- Conceptual framework diagram ----
# Renders the Graphviz source into assets/. Requires the `dot` binary,
# so it is not part of `make all`.
diagrams:
	dot -Tpng assets/conceptual_model.dot -o assets/fig_conceptual_model.png

# ---- Complete local rebuild ----
# Runs every stage that works from files already on disk. Network fetches are
# left manual on purpose. On a fresh clone, run the fetch targets first:
#   make bronze fetch-dev        # network: Binance, Yahoo, FRED, World Bank
#   make all                     # local rebuild and test suite
all: clean features sample spillovers panel robustness decomposition stability \
     stability-coefs leaveouts horse-race tables appendix figures check
